# Generated by Django 5.2.4 on 2025-08-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='categorias')),
            ],
        ),
    ]
