# Generated by Django 5.2.4 on 2025-08-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='desc',
            new_name='descripcion',
        ),
    ]
